"""Zoom connector contract semantics (W11-A).

Pure vendor logic and data for the Zoom connector: identity/UUID encoding,
pagination classification, AI Companion processing tri-state, and Zoom-shape
error mapping plus credential detection. It holds NO network, auth, or dispatch
code. The GENERIC error taxonomy, error envelope, redaction discipline, and
opaque pagination cursor live in the shared W01 control plane
(:mod:`kiro_crew.connections.control_plane`); this package folds into those and
keeps only Zoom-specific semantics. The owning spec is
``docs/system-specs/modules/connector-zoom.md``.
"""

from kiro_crew.connections.vendors.zoom.decoder import (
    ZoomDecodeError,
    decode_list_page,
    decode_single,
    readback_host_id,
)
from kiro_crew.connections.vendors.zoom.dispatch import (
    BUILT_AGAINST_EXECUTOR_SCHEMA,
    BUILT_AGAINST_OPERATION_SCHEMA,
    BUILT_AGAINST_PRODUCTION_SCHEMA,
    BUILT_AGAINST_RESULT_SCHEMA,
    ZOOM_SERVICE_ID,
    ZOOM_SLUG,
    ZoomDispatchError,
    assert_schema_versions,
    attempt_from_outcome,
    build_zoom_transport,
    control_plane_descriptor,
    decode_for,
    dispatch_operation,
    open_page_walk,
    verify_created_host,
    walk_pages,
)
from kiro_crew.connections.vendors.zoom.errors import (
    AMBIGUOUS_ABSENCE_CODE,
    classify_error,
    contains_zoom_credential,
    redact_zoom_secrets,
    zoom_operation_error,
)
from kiro_crew.connections.vendors.zoom.identity import (
    HOST_REACHABILITY_UNKNOWN,
    ZOOM_CREDENTIAL_MODES,
    ZOOM_SERVER_TO_SERVER,
    ZOOM_USER_OAUTH,
    OccurrenceTarget,
    OccurrenceTime,
    encode_uuid_path_segment,
    needs_double_encoding,
    occurrence_target,
    resolve_occurrence_time,
    series_id_for_instances,
)
from kiro_crew.connections.vendors.zoom.locator import (
    CURSOR_ARG,
    DEFAULT_PAGE_SIZE,
    PAGE_SIZE_ARG,
    ZOOM_API_BASE,
    ZoomLocatorError,
    build_request,
    locate,
)
from kiro_crew.connections.vendors.zoom.meetings import (
    MEETINGS_SCHEMA_VERSION,
    OP_CREATE,
    OP_GET,
    OP_LIST,
    OP_UPDATE,
    HostVerification,
    LicenseScope,
    ZoomRequest,
    auth_mode_host_reachability,
    build_create_request,
    build_get_request,
    build_list_request,
    build_update_request,
    descriptor,
    descriptors,
    encode_meeting_uuid_segment,
    license_scope,
    map_error,
    map_list_result,
    map_single_result,
    update_request_target,
    verify_host_readback,
)
from kiro_crew.connections.vendors.zoom.paging import (
    CursorRequest,
    Pagination,
    classify_pagination,
    next_cursor_request,
    to_next_cursor,
)
from kiro_crew.connections.vendors.zoom.processing import (
    SUMMARY_READY_WEBHOOK,
    SummaryState,
    classify_summary_state,
    is_summary_ready_signal,
)

__all__ = [
    "AMBIGUOUS_ABSENCE_CODE",
    "BUILT_AGAINST_EXECUTOR_SCHEMA",
    "BUILT_AGAINST_OPERATION_SCHEMA",
    "BUILT_AGAINST_PRODUCTION_SCHEMA",
    "BUILT_AGAINST_RESULT_SCHEMA",
    "CURSOR_ARG",
    "CursorRequest",
    "DEFAULT_PAGE_SIZE",
    "HOST_REACHABILITY_UNKNOWN",
    "HostVerification",
    "LicenseScope",
    "MEETINGS_SCHEMA_VERSION",
    "OP_CREATE",
    "OP_GET",
    "OP_LIST",
    "OP_UPDATE",
    "OccurrenceTarget",
    "OccurrenceTime",
    "PAGE_SIZE_ARG",
    "Pagination",
    "SUMMARY_READY_WEBHOOK",
    "SummaryState",
    "ZOOM_API_BASE",
    "ZOOM_CREDENTIAL_MODES",
    "ZOOM_SERVER_TO_SERVER",
    "ZOOM_SERVICE_ID",
    "ZOOM_SLUG",
    "ZOOM_USER_OAUTH",
    "ZoomDecodeError",
    "ZoomDispatchError",
    "ZoomLocatorError",
    "ZoomRequest",
    "assert_schema_versions",
    "attempt_from_outcome",
    "auth_mode_host_reachability",
    "build_create_request",
    "build_get_request",
    "build_list_request",
    "build_request",
    "build_update_request",
    "build_zoom_transport",
    "classify_error",
    "classify_pagination",
    "classify_summary_state",
    "contains_zoom_credential",
    "control_plane_descriptor",
    "decode_for",
    "decode_list_page",
    "decode_single",
    "descriptor",
    "descriptors",
    "dispatch_operation",
    "encode_meeting_uuid_segment",
    "encode_uuid_path_segment",
    "is_summary_ready_signal",
    "license_scope",
    "locate",
    "map_error",
    "map_list_result",
    "map_single_result",
    "needs_double_encoding",
    "next_cursor_request",
    "occurrence_target",
    "open_page_walk",
    "readback_host_id",
    "redact_zoom_secrets",
    "resolve_occurrence_time",
    "series_id_for_instances",
    "to_next_cursor",
    "update_request_target",
    "verify_created_host",
    "verify_host_readback",
    "walk_pages",
    "zoom_operation_error",
]
